name: Build EMQX For Test

on:
  workflow_call:
    inputs:
      emqx-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMQX_NAME: ${{ inputs.emqx-name }}
      OTP_VSN: '26.2.5-3'
      ELIXIR_VSN: '1.15.7'


    steps:
      - name: checkout emqx code
        uses: actions/checkout@v3
        with:
          repository: emqx/emqx
          ref: release-58

      - name: build and export to Docker
        id: build
        run: |
          make ${EMQX_NAME}-docker
          echo "_EMQX_DOCKER_IMAGE_TAG=$(head -n 1 .emqx_docker_image_tags)" >> $GITHUB_ENV
      - name: export docker image
        run: |
          docker save $_EMQX_DOCKER_IMAGE_TAG | gzip > $EMQX_NAME-docker.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: '${{ env.EMQX_NAME }}-docker'
          path: '${{ env.EMQX_NAME }}-docker.tar.gz'
          retention-days: 1
